# Generated by Django 4.0.4 on 2022-04-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1000)),
                ('nbr_page_read', models.IntegerField(default=0)),
            ],
        ),
    ]
