# Generated by Django 4.0.4 on 2022-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='text_audio/'),
        ),
    ]
